### ISSUE TITLE
Display/Use issue on localhost

### ISSUE THREAD

**Issue by MongolianMisfit** [wpninjas/ninja-forms-videomail#27]
Upon creating a test form with a Videomail field on localhost, buttons are presented with no functionality and no active/live video pane. 

Below are errors from inspecting element and a screenshot.

<font>`Failed to load resource: the server responded with a status of 404 (Not Found)`</font>
http://localhost/wp-includes/js/jquery/jquery-migrate.min.js
<font>`Uncaught ReferenceError: require is not defined(…)`</font>
http://localhost/wp-content/plugins/ninja-forms-videomail//assets/js/min/videomail.min.js

![videomail error](https://cloud.githubusercontent.com/assets/23242295/20494459/0acfccbc-afeb-11e6-99a2-c091a815d881.png)

**Comment by binarykitchen** [comment]
@MongolianMisfit Hmmm, everything works fine for me. I do not see these errors.

Can you tell me the versions you are using for WordPress, Google Chrome, Ninja Forms and Ninja Forms Videomail altogether?

**Comment by binarykitchen** [comment]
And how did you install the Videomail Ninja Form plugin? Via Git or right as a zip file into WordPress?

**Comment by binarykitchen** [comment]
@MongolianMisfit Ah, I know why. Ignore my previous comments I have deleted. A new version is up and should work now.

(the problem was you didn't have the videomail client and now it's in the repo too)

Let me know if it works now, then feel free to close ticket. Cheers

**Comment by binarykitchen** [comment]
Hmmm, few things still look broken and I need @kjohnson's help. I have renamed the main entry JS file to `main.js` but now WordPress isn't loading it anymore.

@kjohnson Can you spend one minute pretty please and look at this line?
https://github.com/wpninjas/ninja-forms-videomail/blob/master/includes/Fields/Videomail.php#L76

Is there a mistake? Why is this file not loaded anymore?

@MongolianMisfit Hold on with testing, this one needs to be fixed first ...

**Comment by binarykitchen** [comment]
@MongolianMisfit phew, did quite some fixes and it should work again now - can you give the latest version a try and let me know?
